### ISSUE TITLE
LV2 build/release?

### ISSUE THREAD

**Issue by mxmilkiib** [owennjpr/JucePeakSynth#1]
Hi! I was wondering if an LV2 target might be possible at some point in the future? Might need to use a newer version of JUCE though!

**Comment by owennjpr** [comment]
Hi! thanks for reaching out, I believe an LV2 build should definitely be possible with JUCE 7. I can try to get one up to this repo in the next week or two.

**Comment by owennjpr** [comment]
Just pushed an LV2 build! I don't have a great way of testing it on my current system at this time, so let me know if you have any trouble getting it to work!
